//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Screens
{
	using Core;
	using GameObjects;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ChallengeModeScreen : GameScreen
	{
		public virtual object PlayerKnot
		{
			get;
			set;
		}

		public virtual object ChallengeKnot
		{
			get;
			set;
		}

		private World ChallengeWorld
		{
			get;
			set;
		}

		private World PlayerWorld
		{
			get;
			set;
		}

		private KnotRenderer ChallengeKnotRenderer
		{
			get;
			set;
		}

		private KnotRenderer PlayerKnotRenderer
		{
			get;
			set;
		}

		private PipeMovement PlayerKnotMovement
		{
			get;
			set;
		}

		public virtual Stack<Knot> Undo
		{
			get;
			set;
		}

		public virtual Stack<Knot> Redo
		{
			get;
			set;
		}

		public override void Update(GameTime time)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Entered(GameScreen previousScreen, GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

	}
}

