//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Screens
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ControlSettingsScreen : SettingsScreen
	{
		protected virtual object settingsMenu
		{
			get;
			set;
		}

		public override void Update(GameTime time)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Entered(GameScreen previousScreen, GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

		public ControlSettingsScreen(Knot3Game game)
		{
		}

	}
}

