//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Screens
{
	using Core;
    using KnotData;
	using GameObjects;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class CreativeModeScreen : GameScreen
	{
		public virtual Knot Knot
		{
			get;
			set;
		}

		private World World
		{
			get;
			set;
		}

		private KnotRenderer KnotRenderer
		{
			get;
			set;
		}

		public virtual Stack<Knot> Undo
		{
			get;
			set;
		}

		public virtual Stack<Knot> Redo
		{
			get;
			set;
		}

		public override void Update(GameTime time)
		{
			throw new System.NotImplementedException();
		}

		public override void Entered(GameScreen previousScreen, GameTime time)
		{
			throw new System.NotImplementedException();
		}

	}
}

