//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Screens
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Knot3Game : XNA.Game
	{
		public virtual bool IsFullScreen
		{
			get;
			set;
		}

		public virtual Stack<GameScreen> Screens
		{
			get;
			set;
		}

		public virtual bool VSync
		{
			get;
			set;
		}

		public virtual GraphicsDeviceManager Graphics
		{
			get;
			set;
		}

		public virtual IEnumerable<GameScreen> GameScreen
		{
			get;
			set;
		}

		public Knot3Game()
		{
		}

		public override void Draw(GameTime time)
		{
			throw new System.NotImplementedException();
		}

		public override void Initialize()
		{
			throw new System.NotImplementedException();
		}

		public override void UnloadContent()
		{
			throw new System.NotImplementedException();
		}

		public override void Update(GameTime time)
		{
			throw new System.NotImplementedException();
		}

	}
}

