//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Screens
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class MenuScreen : GameScreen
	{
		public override void Update(GameTime time)
		{
			throw new System.NotImplementedException();
		}

		public abstract void Entered(GameScreen previousScreen, GameTime GameTime);

	}
}

