//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Widgets
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ConfirmDialog : Dialog
	{
		private Menu buttons
		{
			get;
			set;
		}

		public ConfirmDialog(GameScreen screen, DisplayLayer drawOrder, string title, string text)
		{
		}

	}
}

