//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Widgets
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class Dialog : Widget, IKeyEventListener, IMouseEventListener
	{
		public virtual string Title
		{
			get;
			set;
		}

		public virtual string Text
		{
			get;
			set;
		}

		public virtual void OnKeyEvent()
		{
			throw new System.NotImplementedException();
		}

		public virtual Rectangle Bounds()
		{
			throw new System.NotImplementedException();
		}

		public virtual void OnLeftClick(Vector2 position, ClickState state, GameTime time)
		{
			throw new System.NotImplementedException();
		}

		public virtual void OnRightClick(Vector2 position, ClickState state, GameTime time)
		{
			throw new System.NotImplementedException();
		}

		public Dialog(GameScreen screen, DisplayLayer drawOrder, string title, string text)
		{
		}

	}
}

