//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Widgets
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class DropDownMenuItem : MenuItem
	{
		private VerticalMenu dropdown
		{
			get;
			set;
		}

		public virtual IEnumerable<DropDownEntry> DropDownEntry
		{
			get;
			set;
		}

		public virtual void AddEntries(DistinctOptionInfo option)
		{
			throw new System.NotImplementedException();
		}

		public virtual void AddEntries(DropDownEntry enties)
		{
			throw new System.NotImplementedException();
		}

		public DropDownMenuItem(GameScreen screen, DisplayLayer drawOrder)
		{
		}

	}
}

