//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Widgets
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum HorizontalAlignment : int
	{
		Left = 0,
		Center = 1,
		Right = 2,
	}
}
