//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Widgets
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class InputItem : MenuItem
	{
		public virtual string InputText
		{
			get;
			set;
		}

		public InputItem(GameScreen screen, DisplayLayer drawOrder, string text)
		{
		}

	}
}

