//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Widgets
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum ItemState : int
	{
		Selected = 1,
		Hovered = 2,
		None = 0,
	}
}
