//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Widgets
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>
	/// Kompositum
	/// 
	/// </remarks>
	public abstract class MenuItem : Widget, IKeyEventListener, IMouseEventListener
	{
		public virtual ItemState ItemState
		{
			get;
			set;
		}

		public virtual int ItemOrder
		{
			get;
			set;
		}

		public virtual string Text
		{
			get;
			set;
		}

		public virtual ItemState ItemState
		{
			get;
			set;
		}

		public abstract void OnLeftClick(Vector2 position, ClickState state, GameTime time);

		public abstract void OnRightClick(Vector2 position, ClickState state, GameTime time);

		public abstract void OnKeyEvent();

		public abstract Rectangle Bounds();

	}
}

