//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Widgets
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class TextInputDialog : ConfirmDialog
	{
		public virtual string InputText
		{
			get;
			set;
		}

		public TextInputDialog(GameScreen screen, DisplayLayer drawOrder, string title, string text, string inputText)
		{
		}

	}
}

