//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum DisplayLayer : int
	{
		None = 0,
		Background = 1,
		GameWorld = 2,
		Dialog = 3,
		Menu = 4,
		MenuItem = 5,
		SubMenu = 6,
		SubMenuItem = 7,
		Overlay = 8,
		Cursor = 9,
	}
}
