//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class DistinctOptionInfo : OptionInfo
	{
		public virtual HashSet<string> ValidValues
		{
			get;
			set;
		}

		public override string Value
		{
			get;
			set;
		}

		public DistinctOptionInfo(string section, string name, string defaultValue, IEnumerable<string> validValues, ConfigFile configFile)
		{
		}

	}
}

