//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class DrawableGameScreenComponent : XNA.DrawableGameComponent, IGameScreenComponent
	{
		public virtual GameScreen Screen
		{
			get;
			set;
		}

		public virtual DisplayLayer Index
		{
			get;
			set;
		}

		public virtual IEnumerable<T> SubComponents(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

		public virtual void DrawableGameStateComponent(GameScreen screen, DisplayLayer index)
		{
			throw new System.NotImplementedException();
		}

	}
}

