//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class FileUtility
	{
		public static string SettingsDirectory
		{
			get;
			set;
		}

		public static string SavegameDirectory
		{
			get;
			set;
		}

		public static string ScreenshotDirectory
		{
			get;
			set;
		}

		public static string ConvertToFileName(string name)
		{
			throw new System.NotImplementedException();
		}

		public virtual string GetHash(string filename)
		{
			throw new System.NotImplementedException();
		}

	}
}

