//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core
{
	using RenderEffects;
	using Screens;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <remarks>
	/// Zustands-Muster (EN: state pattern)
	/// 
	/// Verwaltung der Spielzustände. Jeder Spielzustand hat eine eigene grafische Oberfläche und eigenes Verhalten.
	/// </remarks>
	public abstract class GameScreen
	{
		public virtual Knot3Game Game
		{
			get;
			set;
		}

		public virtual Input Input
		{
			get;
			set;
		}

		public virtual RenderEffect PostProcessingEffect
		{
			get;
			set;
		}

		public virtual RenderEffectStack CurrentRenderEffects
		{
			get;
			set;
		}

		public virtual void Entered(GameScreen previousScreen, GameTime time)
		{
			throw new System.NotImplementedException();
		}

		public virtual void BeforeExit(GameScreen nextScreen, GameTime time)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Update(GameTime time)
		{
			throw new System.NotImplementedException();
		}

		public GameScreen(Knot3Game game)
		{
		}

		public virtual void AddGameComponents(IGameStateComponent[] components)
		{
			throw new System.NotImplementedException();
		}

		public virtual void RemoveGameComponents(IGameStateComponent[] components)
		{
			throw new System.NotImplementedException();
		}

	}
}

