//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IGameScreenComponent  : XNA.IGameComponent
	{
		DisplayLayer Index { get;set; }

		GameScreen Screen { get;set; }

		IEnumerable<T> SubComponents(GameTime time);

	}
}

