//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IMouseEventListener 
	{
		DisplayLayer Index { get;set; }

		bool IsMouseEventEnabled { get;set; }

		DisplayLayer DisplayLayer { get;set; }

		Rectangle Bounds();

		void OnLeftClick(Vector2 position, ClickState state, GameTime time);

		void OnRightClick(Vector2 position, ClickState state, GameTime time);

	}
}

