//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Input : GameScreenComponent
	{
		public virtual ClickState RightMouseButton
		{
			get;
			set;
		}

		public virtual ClickState LeftMouseButton
		{
			get;
			set;
		}

		public virtual MouseState CurrentMouseState
		{
			get;
			set;
		}

		public virtual KeyboardState CurrentKeyboardState
		{
			get;
			set;
		}

		public virtual MouseState PreviousMouseState
		{
			get;
			set;
		}

		public virtual KeyboardState PreviousKeyboardState
		{
			get;
			set;
		}

		public virtual bool GrabMouseMovement
		{
			get;
			set;
		}

		public virtual IEnumerable<ClickState> ClickState
		{
			get;
			set;
		}

		public Input(GameScreen screen)
		{
		}

		public virtual void Update(GameTime time)
		{
			throw new System.NotImplementedException();
		}

	}
}

