//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Localizer
	{
		private static ConfigFile localization
		{
			get;
			set;
		}

		public virtual ConfigFile ConfigFile
		{
			get;
			set;
		}

		public static string Localize(string text)
		{
			throw new System.NotImplementedException();
		}

	}
}

