//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class MousePointer : DrawableGameScreenComponent
	{
		public MousePointer(GameScreen screen)
		{
		}

		public virtual void Draw(GameTime time)
		{
			throw new System.NotImplementedException();
		}

	}
}

