//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class OptionInfo
	{
		private ConfigFile configFile
		{
			get;
			set;
		}

		public virtual string Section
		{
			get;
			set;
		}

		public virtual string Name
		{
			get;
			set;
		}

		public virtual string DefaultValue
		{
			get;
			set;
		}

		public virtual string Value
		{
			get;
			set;
		}

		public virtual ConfigFile ConfigFile
		{
			get;
			set;
		}

		public OptionInfo(string section, string name, string defaultValue, ConfigFile configFile)
		{
		}

	}
}

