//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Options
	{
		public static ConfigFile Default
		{
			get;
			set;
		}

		public virtual ConfigFile ConfigFile
		{
			get;
			set;
		}

	}
}

