//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace Core
{
	using GameObjects;
	using RenderEffects;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class World : DrawableGameScreenComponent, IEnumerable1<IGameObject>
	{
		public virtual Camera Camera
		{
			get;
			set;
		}

		public virtual List<IGameObject> Objects
		{
			get;
			set;
		}

		public virtual IGameObject SelectedObject
		{
			get;
			set;
		}

		public virtual IRenderEffect CurrentEffect
		{
			get;
			set;
		}

		public virtual void Update(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Draw(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

		public World(GameScreen screen)
		{
		}

		public virtual IEnumerator GetEnumerator()
		{
			throw new System.NotImplementedException();
		}

	}
}

