//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace KnotData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ChallengeFileIO : IChallengeIO
	{
		public virtual IEnumerable<KnotStringIO> KnotStringIO
		{
			get;
			set;
		}

		public ChallengeFileIO()
		{
		}

		public virtual void Save(Challenge challenge)
		{
			throw new System.NotImplementedException();
		}

		public virtual Challenge Load(string filename)
		{
			throw new System.NotImplementedException();
		}

		public virtual ChallengeMetaData LoadMetaData(string filename)
		{
			throw new System.NotImplementedException();
		}

	}
}

