//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace KnotData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Challenge
	{
		public virtual Knot Start
		{
			get;
			private set;
		}

		public virtual Knot Target
		{
			get;
			private set;
		}

		private SortedList<Integer, String> highscore
		{
			get;
			set;
		}

		private IChallengeIO format
		{
			get;
			set;
		}

		public virtual IEnumerator<KeyValuePair<String, Integer>> Highscore
		{
			get;
			set;
		}

		public virtual ChallengeMetaData MetaData
		{
			get;
			private set;
		}

		public virtual string Name
		{
			get;
			set;
		}

		public virtual IEnumerable<Knot> Knot
		{
			get;
			set;
		}

		public virtual ChallengeMetaData ChallengeInfo
		{
			get;
			set;
		}

		public Challenge(ChallengeMetaData meta, Knot start, Knot target)
		{
		}

		public virtual void AddToHighscore(string name, int time)
		{
			throw new System.NotImplementedException();
		}

	}
}

