//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace KnotData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ChallengeMetaData
	{
		public virtual string Name
		{
			get;
			set;
		}

		public virtual KnotMetaData Start
		{
			get;
			set;
		}

		public virtual KnotMetaData Target
		{
			get;
			set;
		}

		public virtual IChallengeIO Format
		{
			get;
			set;
		}

		public virtual string Filename
		{
			get;
			set;
		}

		public virtual IEnumerator<KeyValuePair<String, Integer>> Highscore
		{
			get;
			set;
		}

		public ChallengeMetaData(string name, KnotMetaData start, KnotMetaData target, string filename, IChallengeIO format)
		{
		}

	}
}

