//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace KnotData
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Circle<T> : IEnumerable<T>
	{
		public virtual T Content
		{
			get;
			set;
		}

		public virtual Circle<T> Next
		{
			get;
			set;
		}

		public virtual Circle<T> Previous
		{
			get;
			set;
		}

		public virtual Edge Edge
		{
			get;
			set;
		}


		public Circle(T content)
		{
		}

		public virtual void InsertAfter(T next)
		{
			throw new System.NotImplementedException();
		}

		public virtual void InsertBefore(T previous)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Remove()
		{
			throw new System.NotImplementedException();
		}

		public virtual IEnumerator<T> GetEnumerator()
		{
			throw new System.NotImplementedException();
		}

		public virtual IEnumerator GetEnumerator()
		{
			throw new System.NotImplementedException();
		}

	}
}

