//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace KnotData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public enum Direction : int
	{
		Left = 1,
		Right = 2,
		Up = 3,
		Down = 4,
		Forward = 5,
		Backward = 6,
		Zero = 0,
	}
}
