//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace KnotData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Edge
	{
		public virtual Color Color
		{
			get;
			set;
		}

		public virtual Direction Direction
		{
			get;
			private set;
		}

		public virtual List<int> Rectangles
		{
			get;
			set;
		}

		public Edge(Direction direction)
		{
		}

		public virtual Vector3 Get3DDirection()
		{
			throw new System.NotImplementedException();
		}

	}
}

