//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace KnotData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IChallengeIO 
	{
		void Save(Challenge challenge);

		Challenge Load(string filename);

		ChallengeMetaData LoadMetaData(string filename);

	}
}

