//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace KnotData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IKnotIO 
	{
		IEnumerable<string> FileExtensions { get;set; }

		void Save(Knot knot);

		Knot Load(string filename);

		KnotMetaData LoadMetaData(string filename);

	}
}

