//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace KnotData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class KnotFileIO : IKnotIO
	{
		public virtual IEnumerable<string> FileExtensions
		{
			get;
			set;
		}

		public virtual IEnumerable<KnotStringIO> KnotStringIO
		{
			get;
			set;
		}

		public KnotFileIO()
		{
		}

		public virtual void Save(Knot knot)
		{
			throw new System.NotImplementedException();
		}

		public virtual Knot Load(string filename)
		{
			throw new System.NotImplementedException();
		}

		public virtual KnotMetaData LoadMetaData(string filename)
		{
			throw new System.NotImplementedException();
		}

	}
}

