//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace KnotData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class KnotMetaData
	{
		public virtual string Name
		{
			get;
			set;
		}

		public virtual IKnotIO Format
		{
			get;
			private set;
		}

		public virtual Func<Integer> CountEdges
		{
			get;
			private set;
		}

		public virtual string Filename
		{
			get;
			private set;
		}

		public KnotMetaData(string name, Func<Integer> countEdges, IKnotIO format, string filename)
		{
		}

		public KnotMetaData(string name, Func<Integer> countEdges)
		{
		}

	}
}

