//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace KnotData
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class NodeMap
	{
		public virtual Node From(Edge edge)
		{
			throw new System.NotImplementedException();
		}

		public virtual Node To(Edge edge)
		{
			throw new System.NotImplementedException();
		}

		public virtual void OnEdgesChanged()
		{
			throw new System.NotImplementedException();
		}

	}
}

