//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RenderEffects
{
	using Core;
	using GameObjects;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class CelShadingEffect : RenderEffect
	{
		protected virtual void DrawRenderTarget(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

		public override void DrawModel(GameModel GameModel, object GameTime)
		{
			throw new System.NotImplementedException();
		}

		public override void RemapModel(GameModel GameModel)
		{
			throw new System.NotImplementedException();
		}

		public CelShadingEffect(GameScreen screen)
		{
		}

	}
}

