//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RenderEffects
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class FadeEffect : RenderEffect
	{
		private bool IsFinished
		{
			get;
			set;
		}

		private RenderTarget2D PreviousRenderTarget
		{
			get;
			set;
		}

		public FadeEffect(GameScreen newScreen, GameScreen oldScreen)
		{
		}

		protected virtual void DrawRenderTarget(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

	}
}

