//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RenderEffects
{
	using GameObjects;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IRenderEffect 
	{
		RenderTarget2D RenderTarget { get;set; }

		void Begin(object GameTime);

		void End(object GameTime);

		void DrawModel(GameModel model, object GameTime);

		void RemapModel(GameModel model);

	}
}

