//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RenderEffects
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class RenderEffectStack
	{
		public virtual IRenderEffect CurrentEffect
		{
			get;
			set;
		}

		private IRenderEffect DefaultEffect
		{
			get;
			set;
		}

		public virtual IEnumerable<IRenderEffect> IRenderEffect
		{
			get;
			set;
		}

		public virtual IRenderEffect Pop()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Push(IRenderEffect effect)
		{
			throw new System.NotImplementedException();
		}

		public RenderEffectStack(IRenderEffect defaultEffect)
		{
		}

	}
}

