//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RenderEffects
{
	using Core;
	using GameObjects;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class RenderEffect : IRenderEffect
	{
		public virtual RenderTarget2D RenderTarget
		{
			get;
			set;
		}

		protected virtual GameScreen screen
		{
			get;
			set;
		}

		protected virtual SpriteBatch spriteBatch
		{
			get;
			set;
		}

		public virtual void Begin(object GameTime)
		{
			throw new System.NotImplementedException();
		}

		public virtual void End(object GameTime)
		{
			throw new System.NotImplementedException();
		}

		public virtual void DrawModel(GameModel GameModel, object GameTime)
		{
			throw new System.NotImplementedException();
		}

		public virtual void RemapModel(GameModel GameModel)
		{
			throw new System.NotImplementedException();
		}

		protected abstract void DrawRenderTarget(GameTime time);

	}
}

