//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace RenderEffects
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class StandardEffect : RenderEffect
	{
		protected virtual void DrawRenderTarget(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

		public StandardEffect(GameScreen screen)
		{
		}

	}
}

