//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameObjects
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ArrowModelInfo : GameModelInfo
	{
		public virtual Vector3 Direction
		{
			get;
			set;
		}

		public ArrowModelInfo(Vector3 position, Vector3 direction)
		{
		}

	}
}

