//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameObjects
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ArrowModel : GameModel
	{
		public virtual ArrowModelInfo Info
		{
			get;
			set;
		}

		public virtual ArrowModelInfo ArrowModelInfo
		{
			get;
			set;
		}

		public override void Draw(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

		public virtual GameObjectDistance Intersects(Ray ray)
		{
			throw new System.NotImplementedException();
		}

		public ArrowModel(GameScreen screen, ArrowModelInfo info)
		{
		}

		public override void Update(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

	}
}

