//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameObjects
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class GameModelInfo : GameObjectInfo
	{
		public virtual string Modelname
		{
			get;
			set;
		}

		public virtual Angles3 Rotation
		{
			get;
			set;
		}

		public virtual Vector3 Scale
		{
			get;
			set;
		}

		public GameModelInfo(string modelname, Angles3 rotation, Vector3 scale)
		{
		}

	}
}

