//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameObjects
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class GameModel : IGameObject
	{
		public virtual float Alpha
		{
			get;
			set;
		}

		public virtual Color BaseColor
		{
			get;
			set;
		}

		public virtual Color HightlightColor
		{
			get;
			set;
		}

		public virtual float HighlightIntensity
		{
			get;
			set;
		}

		public virtual GameModelInfo Info
		{
			get;
			set;
		}

		public virtual XNA.Model Model
		{
			get;
			set;
		}

		public virtual World World
		{
			get;
			set;
		}

		public virtual Matrix WorldMatrix
		{
			get;
			set;
		}

		public virtual GameModelInfo GameModelInfo
		{
			get;
			set;
		}

		public virtual Vector3 Center()
		{
			throw new System.NotImplementedException();
		}

		public abstract void Update(GameTime GameTime);

		public virtual void Draw(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

		public virtual GameObjectDistance Intersects(Ray Ray)
		{
			throw new System.NotImplementedException();
		}

		public GameModel(GameScreen screen, GameModelInfo info)
		{
		}

	}
}

