//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameObjects
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class GameObjectInfo : IEquatable<GameObjectInfo>
	{
		public virtual bool IsMovable
		{
			get;
			set;
		}

		public virtual bool IsSelectable
		{
			get;
			set;
		}

		public virtual bool IsVisible
		{
			get;
			set;
		}

		public virtual Vector3 Position
		{
			get;
			set;
		}

		public virtual bool Equals(C other)
		{
			throw new System.NotImplementedException();
		}

	}
}

