//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameObjects
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IGameObject 
	{
		GameObjectInfo Info { get;set; }

		World World { get;set; }

		GameObjectInfo GameObjectInfo { get;set; }

		GameObjectDistance GameObjectDistance { get;set; }

		Vector3 Center();

		void Update(GameTime time);

		void Draw(GameTime time);

		GameObjectDistance Intersects(Ray ray);

	}
}

