//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameObjects
{
	using KnotData;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public interface IJunction 
	{
		Edge EdgeFrom { get;set; }

		Edge EdgeTo { get;set; }

	}
}

