//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameObjects
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class KnotInputHandler : GameScreenComponent
	{
		private World world
		{
			get;
			set;
		}

		private GameScreen screen
		{
			get;
			set;
		}

		public virtual void Update(GameTime time)
		{
			throw new System.NotImplementedException();
		}

		public KnotInputHandler(GameScreen screen, World world)
		{
		}

	}
}

