//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameObjects
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ModelFactory
	{
		private Dictionary<GameModelInfo, GameModel> cache
		{
			get;
			set;
		}

		private Func<GameScreen, GameModelInfo, GameModel> createModel
		{
			get;
			set;
		}

		public virtual GameModel this[GameScreen state, GameModelInfo info]
        {
            get
            {
                throw new System.NotImplementedException();
            }
		}

		public ModelFactory(Func<GameScreen, GameModelInfo, GameModel> createModel)
		{
		}

	}
}

