//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameObjects
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ModelMouseHandler : GameScreenComponent
	{
		public virtual void Update(GameTime time)
		{
			throw new System.NotImplementedException();
		}

	}
}

