//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameObjects
{
	using KnotData;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class NodeModelInfo : GameModelInfo, IJunction
	{
		public virtual Edge EdgeFrom
		{
			get;
			set;
		}

		public virtual Edge EdgeTo
		{
			get;
			set;
		}

		public virtual Knot Knot
		{
			get;
			set;
		}

		public virtual Vector3 Position
		{
			get;
			set;
		}

		public NodeModelInfo(Knot knot, Edge from, Edge to)
		{
		}

	}
}

