//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameObjects
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class NodeModel : GameModel
	{
		public virtual NodeModelInfo Info
		{
			get;
			set;
		}

		public virtual NodeModelInfo NodeModelInfo
		{
			get;
			set;
		}

		public NodeModel(GameScreen screen, NodeModelInfo info)
		{
		}

		public override void Draw(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

		public override void Update(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

	}
}

