//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameObjects
{
	using Core;
	using KnotData;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class PipeMovement : IGameObject, IEnumerable1<IGameObject>
	{
		public virtual GameObjectInfo Info
		{
			get;
			set;
		}

		public virtual Knot Knot
		{
			get;
			set;
		}

		public virtual World World
		{
			get;
			set;
		}

		public virtual Vector3 Center()
		{
			throw new System.NotImplementedException();
		}

		public virtual GameObjectDistance Intersects(Ray Ray)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Update(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

		public PipeMovement(GameScreen screen, World world, GameObjectInfo info)
		{
		}

		public virtual IEnumerator GetEnumerator()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Draw(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

	}
}

