//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameObjects
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ShadowGameObject : IGameObject
	{
		public virtual GameObjectInfo Info
		{
			get;
			set;
		}

		public virtual World World
		{
			get;
			set;
		}

		public virtual Vector3 ShadowPosition
		{
			get;
			set;
		}

		public virtual Vector3 OriginalPosition
		{
			get;
			set;
		}

		public virtual Vector3 Center()
		{
			throw new System.NotImplementedException();
		}

		public virtual void Update(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

		public virtual void Draw(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

		public virtual GameObjectDistance Intersects(Ray Ray)
		{
			throw new System.NotImplementedException();
		}

		public ShadowGameObject(GameScreen screen, IGameObject decoratedObj)
		{
		}

	}
}

