//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Wenn der Code neu generiert wird, gehen alle Änderungen an dieser Datei verloren
// </auto-generated>
//------------------------------------------------------------------------------
namespace GameObjects
{
	using Core;
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class ShadowGameModel : ShadowGameObject
	{
		public virtual Color ShadowColor
		{
			get;
			set;
		}

		public virtual float ShadowAlpha
		{
			get;
			set;
		}

		public ShadowGameModel(GameScreen sreen, GameModel decoratedModel)
		{
		}

		public override void Draw(GameTime GameTime)
		{
			throw new System.NotImplementedException();
		}

	}
}

